  version: 2.1
  jobs:
    secret-masking-example:
      docker: 
        - image: circleci/node:4.8.2 
      steps:

        - run: echo $secret1
        - run: echo $short_secret
        - run: echo $boolean_true_secret
        - run: echo $boolean_false_secret
        - run: echo $context_secret
      

workflows:
  version: 2
  build:
    jobs:
      - secret-masking-example

